{
 "title": "Dashboardas su stat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Santykis tarp visu studentu ir studentu 7 klasej",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Studentai_class_id_7_", "legendFormat": "Studentai class id 7 " },
    { "expr": "Studentu_kiekis", "legendFormat": "Studentu kiekis" }
   ]
  },
  {
   "title": "Vidurkis ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "PointCount_Vidurkis", "legendFormat": "PointCount Vidurkis" }
   ]
  },
  {
   "title": "Mixas",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Studentai_class_id_7_", "legendFormat": "Studentai class id 7 " },
    { "expr": "PointCount_Vidurkis", "legendFormat": "PointCount Vidurkis" },
    { "expr": "Prizu_kiekis_filtruotas", "legendFormat": "Prizu kiekis filtruotas" },
    { "expr": "Studentu_kiekis", "legendFormat": "Studentu kiekis" }
   ]
  },
  {
   "title": "panel pavadinimas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "12": 0, "8": 0 },
   "targets": [
    {
     "expr": "PointCount_Vidurkis/Prizu_kiekis_filtruotas",
     "legendFormat": "PointCount Vidurkis/Prizu kiekis filtruotas"
    }
   ]
  }
 ]
}