{
 "title": "Treciasis dashboardas",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "panel pavadinimas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "0": 0 },
   "targets": [
    {
     "expr": "Point_Price_vidurkis*Teacher_COUNT+Teacher_COUNT/Point_Price_vidurkis",
     "legendFormat": "Point Price vidurkis*Teacher COUNT+Teacher COUNT/Point Price vidurkis"
    }
   ]
  },
  {
   "title": "Mokytoju kiekis",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Teacher_COUNT", "legendFormat": "teacher count" }
   ]
  },
  {
   "title": "mix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "Prizu_skaicius", "legendFormat": "ass" },
    {
     "expr": "Prizu_kuriu_taskai_maziau_uz__56_kiekis",
     "legendFormat": "da"
    },
    { "expr": "Teacher_COUNT", "legendFormat": "as" },
    { "expr": "Point_Price_vidurkis", "legendFormat": "ad" }
   ]
  },
  {
   "title": "Prizu skaiciaus palyginimas su prizais kurie maziau uz 56",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "Prizu_kuriu_taskai_maziau_uz__56_kiekis",
     "legendFormat": "mazesni uz 56"
    },
    { "expr": "Prizu_skaicius", "legendFormat": "prc skc" }
   ]
  }
 ]
}